name: csedu_24
description: This the new CSEDU 24 contact list with cool new features.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: '>=1.10.2-pre.54'

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/data/localdb.json
    - assets/images/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
